GET http://127.0.0.1:8000/ HTTP/1.1

### Prueba translate
POST http://127.0.0.1:8000/translate HTTP/1.1
Content-Type: application/json

{
    "id": "video_prueba",
    "url": "https://res.cloudinary.com/ddo7yelan/video/upload/v1726005031/video_prueba.mp4"
}

### Prueba prueba
POST http://127.0.0.1:8000/prueba HTTP/1.1
Content-Type: application/json

{
    "id": 123,
    "translation": "Hola hola"
}