GET https://signai-ml.onrender.com/ HTTP/1.1

### Prueba translate
POST https://signai-ml.onrender.com/translate HTTP/1.1
Content-Type: application/json

{
    "id": 85,
    "url": "https://res.cloudinary.com/ddo7yelan/video/upload/v1726005031/video_prueba.mp4"
}

### Prueba prueba
POST https://signai-ml.onrender.com/prueba HTTP/1.1
Content-Type: application/json

{
    "id": 123,
    "translation": "Hola hola"
}

###
PUT https://sign-ai-web.vercel.app/85/texto HTTP/1.1
Content-Type: application/json

{
    "translation": "HOla como estas"
}