# Utilizar la imagen base de TensorFlow con GPU
FROM tensorflow/tensorflow:latest-gpu

# Establecer el directorio de trabajo
WORKDIR /app

# Pasar argumentos a Docker
ARG CLOUD_NAME
ARG API_KEY
ARG API_SECRET

# Definir variables de entorno
ENV CLOUD_NAME=$CLOUD_NAME
ENV API_KEY=$API_KEY
ENV API_SECRET=$API_SECRET

# Instalar las dependencias del sistema
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 libgtk-3-0 && \
    rm -rf /var/lib/apt/lists/*

# Copiar requirements.txt al contenedor
COPY ./requirements-setto.txt /app/

RUN pip install --no-cache-dir -r requirements-setto.txt
RUN pip install --no-cache-dir jupyter "fastapi[standard]"

# Exponer el puerto para Jupyter
EXPOSE 8888

# Comando para iniciar Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
# docker-compose -f docker-compose-setto.yml build
# docker run --gpus all --memory=30g --env NVIDIA_DISABLE_REQUIRE=1 -e TF_GPU_ALLOCATOR=cuda_malloc_async -it --rm -p 8888:8888 -v C:\Users\48113164\Documents\Github\SignAI-ML:/app signai
#docker run --gpus all --memory=30g --env NVIDIA_DISABLE_REQUIRE=1 -e TF_GPU_ALLOCATOR=cuda_malloc_async -it --rm -p 8888:8888 -v C:\Users\48113164\Documents\Github\SignAI-ML:/app tensorflow/tensorflow:latest-gpu jupyter notebook --notebook-dir=/app/AI-Module/CNN-LSTM --ip=0.0.0.0 --no-browser --allow-root
