services:
  app:
    image: signai
    build:
      context: .
      dockerfile: Dockerfile-setto
      args:
        CLOUD_NAME: ${CLOUD_NAME}
        API_KEY: ${API_KEY}
        API_SECRET: ${API_SECRET}
    environment:
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
