services:
  app:
    image: signai
    build:
      context: ../..
      dockerfile: C:\Users\48113164\Documents\GitHub\SignAI-ML\Docker\Setto\Dockerfile
      args:
        CLOUD_NAME: ${CLOUD_NAME}
        API_KEY: ${API_KEY}
        API_SECRET: ${API_SECRET}
    environment:
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    volumes:
      - ../..:/app