FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

WORKDIR /app

COPY ./requirements-mati.txt /app/
RUN pip install --no-cache-dir -r requirements-mati.txt
RUN pip install --no-cache-dir "fastapi[standard]"
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 libgtk-3-0 ffmpeg && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8000

CMD ["uvicorn", "__init__:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]